version: "1.0"

time_offs:
    types:
        - "Working Nomad"
    statuses:
        - requested
        - approved

teams:
    devs:
        notification:
            - type: slack
              channel: devs
        members:
            - "John Doe"
            - "Mario Rossi"
    marketing:
        notification:
            - type: slack
              channel: marketing
        members:
            - "Jane Doe"
            - "Joe Bloggs"
